In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
sales_data = np.array([
    [1,1500,1800,2000,2200],
    [2,1200,1400,1600,1800],
    [3,2000,2300,2600,2900],
    [4,1800,2100,2400,2700],
    [5,1600,1850,2050,2300]
])

print("=== Sales analysis ===")
print("\n sales data shape",sales_data.shape)
print("\n sales data of first 3 restraurent \n",sales_data[:3, : ])

=== Sales analysis ===

 sales data shape (5, 5)

 sales data of first 3 restraurent 
 [[   1 1500 1800 2000 2200]
 [   2 1200 1400 1600 1800]
 [   3 2000 2300 2600 2900]]


In [22]:
### total sales per year

# print(np.sum(sales_data , axis=0))
yearly_total = np.sum(sales_data[:,1:], axis=0)
print(yearly_total)
min_sales = np.min(sales_data[:,1:],axis=1)
max_sales = np.max(sales_data[:,1:],axis=0)
print("min sales",min_sales)
print("max sales per year",max_sales)

avg_sales = np.mean(sales_data[: , 1:],axis=1)
print("avg sales per restraunt", avg_sales)

monthly_sales = sales_data[:,1:] / 12
print("monthly sales \n",monthly_sales)

[ 8100  9450 10650 11900]
min sales [1500 1200 2000 1800 1600]
max sales per year [2000 2300 2600 2900]
avg sales per restraunt [1875. 1500. 2450. 2250. 1950.]
monthly sales 
 [[125.         150.         166.66666667 183.33333333]
 [100.         116.66666667 133.33333333 150.        ]
 [166.66666667 191.66666667 216.66666667 241.66666667]
 [150.         175.         200.         225.        ]
 [133.33333333 154.16666667 170.83333333 191.66666667]]


In [ ]:
matrix = np.ones((3, 3)) 
print(matrix)
row = np.array([1, 2, 3])
print(row)
print("\n",matrix + row)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 2 3]

 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
