### Q1. Iterate through the following 2D array using nditer and print each element.

In [1]:
import numpy as np

In [3]:
from numpy import nditer


arr = np.array([[1,2,3],[4,5,6]])
for i in np.nditer(arr): 
    print(i)

1
2
3
4
5
6


### Q2. Print indices and values of each element in a 2D array.

In [4]:
for i in np.ndenumerate(arr):
    print(i)

((0, 0), np.int64(1))
((0, 1), np.int64(2))
((0, 2), np.int64(3))
((1, 0), np.int64(4))
((1, 1), np.int64(5))
((1, 2), np.int64(6))


### Q3. Find indices of elements greater than 25.

In [5]:
arr = np.array([1,2,3,5,67,87,57,9])
for i in nditer(arr):
    if i > 25:
        print(i)

67
87
57


### Q4. Sort the array in ascending and descending order.

In [9]:
arr = np.array([1,3,2,4,7,6,9,5])
print(np.sort(arr))

[1 2 3 4 5 6 7 9]


### Q5. Sort rows and columns of a 2D array.

In [11]:
arr = np.array([[1,3,2,7],[4,5,2,1]])
print("row wise: ", np.sort(arr, axis=1))
print("column wise: ", np.sort(arr, axis=0))

row wise:  [[1 2 3 7]
 [1 2 4 5]]
column wise:  [[1 3 2 1]
 [4 5 2 7]]


### Q6. Find the index where value 6 should be inserted in sorted array [1, 3, 5, 7, 9].

In [12]:
arr = np.array([1,3,4,7,9])
print("index: ", np.searchsorted(arr,6))

index:  3


### Q7. Find where to insert 5 using side='left' and side='right'.

In [16]:
print("from right index:",np.searchsorted(arr,6,side='left'))

from right index: 3


### Q8. Iterate a 3D array using nditer and print all values in a single line.

In [18]:
arr = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


### . Print only the elements on the diagonal using ndenumerate.

In [19]:
from numpy import ndenumerate


arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

for i , j in np.ndenumerate(arr):
      if i[0] == i [1]:
            print(i,j) 

(0, 0) 10
(1, 1) 50
(2, 2) 90


### Q10. Replace negative numbers with 0 using ndenumerate.

In [26]:
arr = np.array([1,-2,3,-4,-5,6,-3])
for i, j in np.ndenumerate(arr):
    if j < 0:
        arr[i] = 0
print(arr)


[1 0 3 0 0 6 0]


### Q11.  Find even numbers and their indices

In [27]:
for i , j in np.ndenumerate(arr):
    if j%2 == 0:
        print(i,j)

(1,) 0
(3,) 0
(4,) 0
(5,) 6
(6,) 0


### Q12. Replace all numbers greater than 50 with 100.

In [28]:
arr = np.array([20, 55, 40, 90, 10, 60])

arr[arr > 50] = 100

print(arr)

[ 20 100  40 100  10 100]


### Q13. Sort a 2D array column-wise.

In [31]:
arr = np.array([
    [101, 20, 3],
    [40, 501, 6],
    [701, 8, 90]
])

print(np.sort(arr, axis=1))

[[  3  20 101]
 [  6  40 501]
 [  8  90 701]]


###  Q14. Insert multiple values [4, 10] in sorted array [1, 3, 5, 7, 9].

In [34]:


arr = np.array([1,3,5,7,9])
values = np.array([4,10])
idx =  np.searchsorted(arr,values)
print(np.insert(arr, idx, values ))

[ 1  3  4  5  7  9 10]


### Q15. Insert values [2, 8] into sorted array and actually insert them.

In [35]:
arr = np.array([1,3,5,7,9])
values = np.array([2,8])
idx =  np.searchsorted(arr,values)
print(np.insert(arr, idx, values ))

[1 2 3 5 7 8 9]
