### question 1


In [1]:
import numpy as np

In [5]:
arr = np.array([10,20,30,40])
print("Its datatype: ", arr.dtype)
arr2 = np.array([1.5,2.7,3.8])
print("convert to int: ", arr2.astype(int))

Its datatype:  int64
convert to int:  [1 2 3]


In [6]:
arr = np.array([True,False,True])
print("convert to float: ",arr.astype(float))

convert to float:  [1. 0. 1.]


In [7]:
arr = np.array([1,2,'3',4])
print(arr.dtype)

<U21


In [12]:


arr = np.array(['1','2','3'])
arr2 = arr.astype(int)
print(arr2)
print(arr2.dtype)

[1 2 3]
int64


In [ ]:

arr = np.array([10,20,30])
arr2 = arr.astype(str)
print(arr2, arr2.dtype)

['10' '20' '30'] <U21


In [14]:
arr = np.array([[1,2],[3,4]])
print(arr.astype(float))

[[1. 2.]
 [3. 4.]]


In [15]:
obj = np.object_([10,'hello',3.5])
print(obj.dtype)

object


In [16]:
arr = np.array([1.2,3.5,5.7])
print("convert to boolean : ", arr.astype(bool))

convert to boolean :  [ True  True  True]


In [18]:
arr = np.array([65,66,67])
print("convert", arr.astype(str).dtype)

convert <U21


In [24]:
arr = np.array([1,2,3,4])
x = arr.copy()
x[1]= 100
print(x,arr)
print("..............")
arr2 = np.array([1,2,3,4])
y = arr2.view()
y[2]= 100
print(y,arr2)


[  1 100   3   4] [1 2 3 4]
..............
[  1   2 100   4] [  1   2 100   4]


### Reshaping array


In [30]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("2d",a.reshape(3,4))
b = a.reshape(3,2,2)
print("3d",a.reshape(3,2,2))
# print(b)
print(b.reshape(-1))

2d [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3d [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


Reshape Practice Questions

Create an array a = [1, 2, 3, 4, 5, 6] and reshape it into a 2×3 array.

Create an array b = [1, 2, 3, 4, 5, 6, 7, 8] and reshape it into a 4×2 array.

Reshape the array c = np.arange(12) into a 3×4 array.

Reshape d = np.arange(8) into a 2×2×2 3D array.

Use -1 to automatically infer one dimension: reshape e = np.arange(12) into a 3×? array.

Flatten a 2D array f = [[1, 2, 3], [4, 5, 6]] into 1D.

Reshape a 3D array g = np.arange(24).reshape(2, 3, 4) into 4×6.

Given h = np.array([1, 2, 3, 4, 5, 6]), try reshaping into 4×2 (should it work? Why/why not?) notttttttt

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.reshape(2,3))

arr2 = np.array([1,2,3,4,5,6,7,8])
print(arr2.reshape(4,2))
arr3 = np.arange(12)
print(arr3.reshape(3,4))
arr4 = np.arange(8)
print(arr4.reshape(2,2,2))

arr5 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr5.reshape(-1))

h = np.array([1, 2, 3, 4, 5, 6])

# print(h.reshape(4,2))  not possible

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[1 2 3 4 5 6]
